/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EquipmentMaintenaceTeam;

import Business.Department.DepartmentClass;
import Business.Department.EngineeringDepartment;
import Business.Department.EquipmentMaintenanceDepartment;
import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.EquipmentMaintenance.EquipmentMaintenanceDetails;
import Business.EquipmentMaintenance.EquipmentMaintenanceDirectory;
import Business.OrderDirectory;
import Business.Orders;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lsrajput
 */
public class equipmentMaintenanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form equipmentMaintenanceJPanel
     */
    private JPanel displayJPanel;
    private OrderDirectory orderDir;
    private EmployeeDirectory empDir;
    private EquipmentMaintenanceDirectory emTeamDir;
    
    private UserAccount account;
    private DepartmentClass department;
    private Enterprise enterprise;
    private Ecosystem ecosystem;
    public equipmentMaintenanceJPanel(JPanel displayPanel, UserAccount account, DepartmentClass department, Enterprise enterprise,Ecosystem ecosystem) {
        initComponents();
        this.displayJPanel = displayPanel;
        this.department = department;
        this.enterprise = enterprise;
        this.account = account;
        this.ecosystem = ecosystem;
        Employee emp = account.getEmployee();
        fnameTxtField.setText(account.getEmployee().getFirstName());
        fnameTxtField.setEditable(false);
        empIDTxtfield.setText(account.getEmployee().getEmployeeId()+"");
        empIDTxtfield.setEditable(false);
        if(emp.getDateOfBirth()!=null)
        {
           dobTextField.setText(emp.getDateOfBirth());
        }
        if(emp.getLastName()!=null)
        {
            lnameTxtField.setText(emp.getLastName());
        }
        if(emp.getDesignation()!=null)
        {
            designationjComboBox.setSelectedItem(emp.getDesignation());
        }
        if(emp.getTeamType()!=null)
        {
            teamTypeTxtField.setText(emp.getTeamType());
        }
        if(emp.getSalary()!=null)
        {
            salaryTxtField.setText(emp.getSalary());
        }
        orderDir = new OrderDirectory();
        populateTable();
    }

    private void populateSalary() {
        if(designationjComboBox.getSelectedItem()=="Trainee Consultant")
      {
          salaryTxtField.setText("20000.00");
      }
      else if(designationjComboBox.getSelectedItem()=="Junior Consultant")
      {
          salaryTxtField.setText("22500.00");
      }
      else if(designationjComboBox.getSelectedItem()=="Senior Consultant")
      {
          salaryTxtField.setText("25000.00");
      }
      else
      {
          salaryTxtField.setText("40000.00");
      }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        
        for (DepartmentClass dept : ecosystem.getNetworkList().get(0).getDepartmentDirectory().getDepartmentList()){
            if(dept instanceof EquipmentMaintenanceDepartment)
            {
                for(EquipmentMaintenanceDetails equipmentMaintenanceDetails: ((EquipmentMaintenanceDepartment) dept).getEquipmentMaintananceDirectory().getEquipmentMaintananceList())
                {
                    for(WorkQueue workQueue: equipmentMaintenanceDetails.getWorkQueueDirectory().getWorkQueueList())
                    {
                        Object[] row = new Object[4];
                        row[0] = workQueue.getId();
                        row[1] = workQueue.getDate();
                        row[2] = workQueue.getTask();
                        row[3] = workQueue.getStatus();
                        model.addRow(row);
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GSMCJLabel = new javax.swing.JLabel();
        WelcomeJLabel = new javax.swing.JLabel();
        PDJLabel = new javax.swing.JLabel();
        empIDJLabel = new javax.swing.JLabel();
        fnameJLabel = new javax.swing.JLabel();
        lnameJLabel = new javax.swing.JLabel();
        dobJLabel = new javax.swing.JLabel();
        WDJLabel = new javax.swing.JLabel();
        teamTypeJLabel = new javax.swing.JLabel();
        designationJLabel = new javax.swing.JLabel();
        salaryJLabel = new javax.swing.JLabel();
        empIDTxtfield = new javax.swing.JTextField();
        fnameTxtField = new javax.swing.JTextField();
        lnameTxtField = new javax.swing.JTextField();
        teamTypeTxtField = new javax.swing.JTextField();
        salaryTxtField = new javax.swing.JTextField();
        designationjComboBox = new javax.swing.JComboBox();
        workQueueJlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        acknowledgeBtn = new javax.swing.JButton();
        completeBtn = new javax.swing.JButton();
        raisearequestJLabel = new javax.swing.JLabel();
        targetTeamRRJLabel = new javax.swing.JLabel();
        teamTypeRRComboBox = new javax.swing.JComboBox();
        issueDescJlabel = new javax.swing.JLabel();
        checkInventoryJlabel = new javax.swing.JButton();
        orderNewEquipmentJLabel = new javax.swing.JLabel();
        deviceNameJlabel = new javax.swing.JLabel();
        deviceNameComboBox = new javax.swing.JComboBox();
        noOfUnitsjlabel = new javax.swing.JLabel();
        noOfUnitsComboBox = new javax.swing.JComboBox();
        submitBtn = new javax.swing.JButton();
        submit1Btn = new javax.swing.JButton();
        submit2Btn = new javax.swing.JButton();
        dobTextField = new javax.swing.JTextField();
        issuejTextField1 = new javax.swing.JTextField();

        GSMCJLabel.setText("Grey-Sloan Medical Centre");

        WelcomeJLabel.setText("Welcome <Ria Rajput>");

        PDJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PDJLabel.setText("Personal Details");

        empIDJLabel.setText("Employee ID :");

        fnameJLabel.setText("First Name :");

        lnameJLabel.setText("Last Name :");

        dobJLabel.setText("Date of Birth :");

        WDJLabel.setText("Work Details");

        teamTypeJLabel.setText("Team Type :");

        designationJLabel.setText("Designation :");

        salaryJLabel.setText("Salary :");

        teamTypeTxtField.setText("Equipment maintenace team");
        teamTypeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamTypeTxtFieldActionPerformed(evt);
            }
        });

        designationjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Trainee Consultant", "Consultant", "Senior Consultant", "Manager" }));
        designationjComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                designationjComboBoxItemStateChanged(evt);
            }
        });

        workQueueJlabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        workQueueJlabel.setText("Work Queue");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "Date", "Task", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        acknowledgeBtn.setText("Acknowledge");
        acknowledgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acknowledgeBtnActionPerformed(evt);
            }
        });

        completeBtn.setText("Complete");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        raisearequestJLabel.setText("Raise a request");

        targetTeamRRJLabel.setText("Target Team :");

        teamTypeRRComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Engineering Team", "Tech Support Team" }));
        teamTypeRRComboBox.setToolTipText("For any order requests other than the functional teams of GSMC,kindly select System Admin");

        issueDescJlabel.setText("Issue Description : ");

        checkInventoryJlabel.setText("Check Inventory");
        checkInventoryJlabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInventoryJlabelActionPerformed(evt);
            }
        });

        orderNewEquipmentJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        orderNewEquipmentJLabel.setText("Order new equipment  ");

        deviceNameJlabel.setText("Device Name :");

        deviceNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Medical Glove", "Scalpel", "Thermometer", "Syringe", "Catheter" }));

        noOfUnitsjlabel.setText("Number of units :");

        noOfUnitsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        submit1Btn.setText("Submit");
        submit1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1BtnActionPerformed(evt);
            }
        });

        submit2Btn.setText("Submit");
        submit2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2BtnActionPerformed(evt);
            }
        });

        dobTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(targetTeamRRJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(teamTypeRRComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deviceNameJlabel)
                                .addGap(18, 18, 18)
                                .addComponent(deviceNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(noOfUnitsjlabel)
                            .addComponent(issueDescJlabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(issuejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(noOfUnitsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WelcomeJLabel)
                            .addComponent(PDJLabel)
                            .addComponent(WDJLabel)
                            .addComponent(workQueueJlabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fnameJLabel)
                                .addGap(280, 280, 280)
                                .addComponent(lnameJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(lnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(dobJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(teamTypeJLabel)
                                            .addComponent(salaryJLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(salaryTxtField)
                                            .addComponent(teamTypeTxtField))))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(empIDJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(empIDTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(designationJLabel)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(designationjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(GSMCJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(acknowledgeBtn)
                        .addGap(19, 19, 19)
                        .addComponent(completeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkInventoryJlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(raisearequestJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(orderNewEquipmentJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(submit2Btn)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submit1Btn)
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GSMCJLabel)
                .addGap(18, 18, 18)
                .addComponent(WelcomeJLabel)
                .addGap(18, 18, 18)
                .addComponent(PDJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameJLabel)
                    .addComponent(fnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameJLabel)
                    .addComponent(lnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobJLabel)
                    .addComponent(empIDJLabel)
                    .addComponent(empIDTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(WDJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamTypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teamTypeJLabel)
                        .addComponent(designationJLabel)
                        .addComponent(designationjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryJLabel)
                    .addComponent(salaryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workQueueJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acknowledgeBtn)
                    .addComponent(completeBtn)
                    .addComponent(checkInventoryJlabel))
                .addGap(18, 18, 18)
                .addComponent(raisearequestJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetTeamRRJLabel)
                    .addComponent(teamTypeRRComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueDescJlabel)
                    .addComponent(issuejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit1Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(orderNewEquipmentJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deviceNameJlabel)
                    .addComponent(deviceNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfUnitsjlabel)
                    .addComponent(noOfUnitsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit2Btn)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void teamTypeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamTypeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamTypeTxtFieldActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String firstName = fnameTxtField.getText();
        String lastName = lnameTxtField.getText();
        int employeeId = Integer.parseInt(empIDTxtfield.getText());
        String designation = designationjComboBox.getSelectedItem().toString();
        String dob = dobTextField.getText();
        String salary = salaryTxtField.getText();
        String teamType = teamTypeTxtField.getText();
        System.out.println("employeeId: "+employeeId);
        boolean isUpdated = false;
        for(DepartmentClass dep: ecosystem.getNetworkList().get(0).getDepartmentDirectory().getDepartmentList())
        {
            for(UserAccount user:dep.getUserDir().getUserAccountsList())
            {
                Employee emp = user.getEmployee();
                System.out.println("emp.getEmployeeId(): "+emp.getEmployeeId());
                if(emp.getEmployeeId()==employeeId)
                {
                    System.out.println("Updating employee details");
                    emp.setDateOfBirth(dob);
                    emp.setLastName(lastName);
                    emp.setDesignation(designation);
                    emp.setSalary(salary);
                    emp.setTeamType(teamType);
                    isUpdated = true;
                    break;
                }
            }
            if(isUpdated)
                break;
        }
        JOptionPane.showMessageDialog(displayJPanel,"Updated Successfully!");
    }//GEN-LAST:event_submitBtnActionPerformed

    private void submit2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2BtnActionPerformed
        // TODO add your handling code here:
        String deviceName = deviceNameComboBox.getSelectedItem().toString();
        System.out.print("Device name = " + deviceName);
        String noOfUnits = noOfUnitsComboBox.getSelectedItem().toString();
        System.out.print("No of units = " + noOfUnits);
        Orders order = orderDir.addnewOrder();
        System.out.println("next line");
        order.setDeviceName(deviceName);
        order.setNoOfUnits(noOfUnits);
        order.setCost(120);
        order.setIssueDesc("");
        order.setStatus("Pending");
        order.setOrderId(101);
        order.setPlacedBy("Equipment Maintenance Team");
        Date orderDate = new Date();
        order.setDate(orderDate);
        System.out.println(order.getDate());
        
        CardLayout layout = (CardLayout)displayJPanel.getLayout();
        this.displayJPanel.add(new OrdersJPanel(this.displayJPanel, orderDir, ecosystem));
        layout.next(this.displayJPanel);
    }//GEN-LAST:event_submit2BtnActionPerformed

    private void dobTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextFieldActionPerformed

    private void acknowledgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acknowledgeBtnActionPerformed
        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        int taskId = 0;
        System.out.println("row: "+row+" column: "+column+" value: "+jTable1.getValueAt(row, column));
        try{
            taskId = (Integer)jTable1.getValueAt(row, column);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(displayJPanel,"Select valid Task ID.");
            return;
        }
        for (DepartmentClass dept : ecosystem.getNetworkList().get(0).getDepartmentDirectory().getDepartmentList()){
            if(dept instanceof EquipmentMaintenanceDepartment)
            {
                for(EquipmentMaintenanceDetails equipmentMaintenanceDetails: ((EquipmentMaintenanceDepartment) dept).getEquipmentMaintananceDirectory().getEquipmentMaintananceList())
                {
                    for(WorkQueue workQueue: equipmentMaintenanceDetails.getWorkQueueDirectory().getWorkQueueList())
                    {
                        if(workQueue.getId()==taskId)
                        {
                            workQueue.setStatus("Acknowledged");
                        }
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(displayJPanel,"Your Acknowledgement received!");
         populateTable();
    }//GEN-LAST:event_acknowledgeBtnActionPerformed

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        int taskId = 0;
        System.out.println("row: "+row+" column: "+column+" value: "+jTable1.getValueAt(row, column));
        try{
            taskId = (Integer)jTable1.getValueAt(row, column);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(displayJPanel,"Select valid Task ID.");
            return;
        }
        for (DepartmentClass dept : ecosystem.getNetworkList().get(0).getDepartmentDirectory().getDepartmentList()){
            if(dept instanceof EquipmentMaintenanceDepartment)
            {
                for(EquipmentMaintenanceDetails equipmentMaintenanceDetails: ((EquipmentMaintenanceDepartment) dept).getEquipmentMaintananceDirectory().getEquipmentMaintananceList())
                {
                    for(WorkQueue workQueue: equipmentMaintenanceDetails.getWorkQueueDirectory().getWorkQueueList())
                    {
                        if(workQueue.getId()==taskId)
                        {
                            equipmentMaintenanceDetails.getWorkQueueDirectory().getWorkQueueList().remove(workQueue);
                            break;
                        }
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(displayJPanel,"Task completed!");
         populateTable();
    }//GEN-LAST:event_completeBtnActionPerformed

    private void checkInventoryJlabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInventoryJlabelActionPerformed
        CardLayout layout = (CardLayout)this.displayJPanel.getLayout();
        this.displayJPanel.add(new InventoryJPanel(displayJPanel));
        layout.next(displayJPanel);
    }//GEN-LAST:event_checkInventoryJlabelActionPerformed

    private void submit1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1BtnActionPerformed
        String teamType = (String)teamTypeRRComboBox.getSelectedItem();
        String issueDesc = issuejTextField1.getText();
        if("Equipment Maintenance Team".equalsIgnoreCase(teamType))
        {
            try
            {
                for(DepartmentClass dept: ecosystem.getNetworkList().get(0).getDepartmentDirectory().getDepartmentList())
                {
                    if(dept instanceof EquipmentMaintenanceDepartment)
                    {
                        ((EquipmentMaintenanceDepartment) dept).getEquipmentMaintananceDirectory().getEquipmentMaintananceList().get(0).getWorkQueueDirectory().createWorkQueue(issueDesc);

                    }
                }
                JOptionPane.showMessageDialog(displayJPanel,"Work Queue added to Equipment Maintenance Team.");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(displayJPanel,"Equipment Maintenance team not available");
            }
            
        }
        else if("Engineering Team".equalsIgnoreCase(teamType))
        {
            try
            {
                for(DepartmentClass dept: ecosystem.getNetworkList().get(0).getDepartmentDirectory().getDepartmentList())
                {
                    if(dept instanceof EngineeringDepartment)
                    {
                        ((EngineeringDepartment) dept).getEngineeringTeamDirectory().getEnggTeamList().get(0).getWorkQueueDirectory().createWorkQueue(issueDesc);
                    }
                }
                JOptionPane.showMessageDialog(displayJPanel,"Work Queue added to Egineering Team.");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(displayJPanel,"Engineering team not available");
            }
            
        }
        else if("Tech Support Team".equalsIgnoreCase(teamType))
        {
            try
            {
                for(DepartmentClass dept: ecosystem.getNetworkList().get(0).getDepartmentDirectory().getDepartmentList())
                {
                    if(dept instanceof EngineeringDepartment)
                    {
                        ((EngineeringDepartment) dept).getEngineeringTeamDirectory().getEnggTeamList().get(0).getWorkQueueDirectory().createWorkQueue(issueDesc);
                    }
                }
                JOptionPane.showMessageDialog(displayJPanel,"Work Queue added to Egineering Team.");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(displayJPanel,"Engineering team not available");
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(displayJPanel,"Selected team not available");
        }
    }//GEN-LAST:event_submit1BtnActionPerformed

    private void designationjComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_designationjComboBoxItemStateChanged
        // TODO add your handling code here:
        populateSalary();
    }//GEN-LAST:event_designationjComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GSMCJLabel;
    private javax.swing.JLabel PDJLabel;
    private javax.swing.JLabel WDJLabel;
    private javax.swing.JLabel WelcomeJLabel;
    private javax.swing.JButton acknowledgeBtn;
    private javax.swing.JButton checkInventoryJlabel;
    private javax.swing.JButton completeBtn;
    private javax.swing.JLabel designationJLabel;
    private javax.swing.JComboBox designationjComboBox;
    private javax.swing.JComboBox deviceNameComboBox;
    private javax.swing.JLabel deviceNameJlabel;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel empIDJLabel;
    private javax.swing.JTextField empIDTxtfield;
    private javax.swing.JLabel fnameJLabel;
    private javax.swing.JTextField fnameTxtField;
    private javax.swing.JLabel issueDescJlabel;
    private javax.swing.JTextField issuejTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lnameJLabel;
    private javax.swing.JTextField lnameTxtField;
    private javax.swing.JComboBox noOfUnitsComboBox;
    private javax.swing.JLabel noOfUnitsjlabel;
    private javax.swing.JLabel orderNewEquipmentJLabel;
    private javax.swing.JLabel raisearequestJLabel;
    private javax.swing.JLabel salaryJLabel;
    private javax.swing.JTextField salaryTxtField;
    private javax.swing.JButton submit1Btn;
    private javax.swing.JButton submit2Btn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel targetTeamRRJLabel;
    private javax.swing.JLabel teamTypeJLabel;
    private javax.swing.JComboBox teamTypeRRComboBox;
    private javax.swing.JTextField teamTypeTxtField;
    private javax.swing.JLabel workQueueJlabel;
    // End of variables declaration//GEN-END:variables
}
