/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EquipmentMaintenaceTeam;

import Business.Ecosystem;
import Business.OrderDirectory;
import Business.Orders;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lsrajput
 */
public class OrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrdersJPanel
     */
    
    private JPanel displayJPanel;
    private OrderDirectory orderDir;
    private Ecosystem ecosystem;
    public OrdersJPanel(JPanel displayJPanel,OrderDirectory orderDir, Ecosystem ecosystem) {
        initComponents();
        this.displayJPanel = displayJPanel;
        this.orderDir = orderDir;
        this.ecosystem = ecosystem;
        populateNewOrdersTable();
        
    }
    public void populateNewOrdersTable()
    {
        DefaultTableModel dtm =  (DefaultTableModel)newOrdersJTable.getModel();
        dtm.setRowCount(0);
        Date date = new Date();
        Double amount = 0.0;
        for(Orders order : orderDir.getOrderDirectory())
        {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]= date;
            row[1]= order.getOrderId();
            row[2]= order.getDeviceName();
            row[3]= order.getPlacedBy();
            row[4]= order.getNoOfUnits();
            row[5]= order.getCost();
            amount+= (order.getCost() * Integer.parseInt(order.getNoOfUnits()));
            dtm.addRow(row);
        }
        grossOrderPriceTxtField.setText(""+amount);
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GSMCJLabel = new javax.swing.JLabel();
        omJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newOrdersJTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        grossOrderpriceTxtField = new javax.swing.JLabel();
        grossOrderPriceTxtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        GSMCJLabel.setText("Grey-Sloan Medical Centre");

        omJLabel.setText("Order Management Table ");

        jLabel1.setText("New Orders");

        newOrdersJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Order ID", "Device Type", "Placed By", "No of Equipments", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(newOrdersJTable);
        if (newOrdersJTable.getColumnModel().getColumnCount() > 0) {
            newOrdersJTable.getColumnModel().getColumn(0).setResizable(false);
            newOrdersJTable.getColumnModel().getColumn(1).setResizable(false);
            newOrdersJTable.getColumnModel().getColumn(2).setResizable(false);
            newOrdersJTable.getColumnModel().getColumn(3).setResizable(false);
            newOrdersJTable.getColumnModel().getColumn(4).setResizable(false);
            newOrdersJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        grossOrderpriceTxtField.setText("Gross Orders Price :");

        jButton1.setText("Send Order to Medical Equipment Supplier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(GSMCJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(omJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(grossOrderpriceTxtField)
                        .addGap(92, 92, 92)
                        .addComponent(grossOrderPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GSMCJLabel)
                .addGap(36, 36, 36)
                .addComponent(omJLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossOrderpriceTxtField)
                    .addComponent(grossOrderPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(jButton1))
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.displayJPanel.remove(this);
        CardLayout layout = (CardLayout)this.displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ecosystem.getNetworkList().get(0).setOrderDirectory(orderDir);
        JOptionPane.showMessageDialog(displayJPanel,"Order sent to Medical Equipment Supplier!");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GSMCJLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField grossOrderPriceTxtField;
    private javax.swing.JLabel grossOrderpriceTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable newOrdersJTable;
    private javax.swing.JLabel omJLabel;
    // End of variables declaration//GEN-END:variables
}
