/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicalEquipmentSupplier;

import Business.Department.DepartmentClass;
import Business.Ecosystem;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.EquipmentMaintenance.EquipmentMaintenanceDirectory;
import Business.OrderDirectory;
import Business.Orders;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.EquipmentMaintenaceTeam.InventoryJPanel;

/**
 *
 * @author lsrajput
 */
public class OrderTableJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderTableJPanel
     */
    private JPanel displayJPanel;
    private UserAccount account;
    private DepartmentClass department;
    private Enterprise enterprise;
    private Ecosystem ecosystem;
    public OrderTableJPanel(JPanel displayPanel, UserAccount account, DepartmentClass department, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.displayJPanel = displayPanel;
        this.department = department;
        this.enterprise = enterprise;
        this.account = account;
        this.ecosystem = ecosystem;
        populateNewOrdersTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        oderreqtbl = new javax.swing.JTable();
        ackbtn = new javax.swing.JButton();
        completeBtn = new javax.swing.JButton();
        inventoryBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Order Request Table:");

        oderreqtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Equipment Name", "No.of units required", "Enterprise Name", "Status"
            }
        ));
        oderreqtbl.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(oderreqtbl);
        oderreqtbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (oderreqtbl.getColumnModel().getColumnCount() > 0) {
            oderreqtbl.getColumnModel().getColumn(0).setResizable(false);
            oderreqtbl.getColumnModel().getColumn(1).setResizable(false);
            oderreqtbl.getColumnModel().getColumn(2).setResizable(false);
            oderreqtbl.getColumnModel().getColumn(3).setResizable(false);
            oderreqtbl.getColumnModel().getColumn(4).setResizable(false);
        }

        ackbtn.setText("Acknowledge");
        ackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ackbtnActionPerformed(evt);
            }
        });

        completeBtn.setText("Completed");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        inventoryBtn.setText("Inventory");
        inventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 61, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ackbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(completeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ackbtn)
                    .addComponent(completeBtn)
                    .addComponent(inventoryBtn))
                .addGap(0, 236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateNewOrdersTable()
    {
        DefaultTableModel dtm =  (DefaultTableModel)oderreqtbl.getModel();
        dtm.setRowCount(0);
        for(Orders order : ecosystem.getNetworkList().get(0).getOrderDirectory().getOrderDirectory())
        {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]= order.getOrderId();
            row[1]= order.getDeviceName();
            row[2]= order.getNoOfUnits();
            row[3]= order.getPlacedBy();
            row[4]= order.getStatus();
            dtm.addRow(row);
        }
    }  
    private void ackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ackbtnActionPerformed
        int row = oderreqtbl.getSelectedRow();
        int column = oderreqtbl.getSelectedColumn();
        int orderId = 0;
        try{
            orderId = (Integer)oderreqtbl.getValueAt(row, column);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(displayJPanel,"Select valid Order ID.");
            return;
        }
        for(Orders order : ecosystem.getNetworkList().get(0).getOrderDirectory().getOrderDirectory())
        {
            if(order.getOrderId()==orderId)
            {
                order.setStatus("Acknowledged");
                break;
            }
        }
        JOptionPane.showMessageDialog(displayJPanel,"Your Acknowledgement received!");
        populateNewOrdersTable();
    }//GEN-LAST:event_ackbtnActionPerformed

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        int row = oderreqtbl.getSelectedRow();
        int column = oderreqtbl.getSelectedColumn();
        int orderId = 0;
        try{
            orderId = (Integer)oderreqtbl.getValueAt(row, column);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(displayJPanel,"Select valid Order ID.");
            return;
        }
        for(Orders order : ecosystem.getNetworkList().get(0).getOrderDirectory().getOrderDirectory())
        {
            if(order.getOrderId()==orderId)
            {
                ecosystem.getNetworkList().get(0).getOrderDirectory().getOrderDirectory().remove(order);
                break;
            }
        }
        JOptionPane.showMessageDialog(displayJPanel,"Order completed!");
        populateNewOrdersTable();
    }//GEN-LAST:event_completeBtnActionPerformed

    private void inventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryBtnActionPerformed
        CardLayout layout = (CardLayout)this.displayJPanel.getLayout();
        this.displayJPanel.add(new InventoryJPanel(displayJPanel));
        layout.next(displayJPanel);
    }//GEN-LAST:event_inventoryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ackbtn;
    private javax.swing.JButton completeBtn;
    private javax.swing.JButton inventoryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable oderreqtbl;
    // End of variables declaration//GEN-END:variables
}
