/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysadminRole;

import Business.Department.DepartmentClass;
import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lsrajput
 */
public class ManageEmployeesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDepartmentsJPanel
     */
    private JPanel displayJPanel;
    private Ecosystem ecosystem;
    public ManageEmployeesJPanel(JPanel displayJPanel,Ecosystem ecosystem) {
        initComponents();
        this.displayJPanel = displayJPanel;
        this.ecosystem = ecosystem;
        populateTable();
        populateDepartmentComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        departmentJLabel = new javax.swing.JLabel();
        departmentjComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        newEmployeeJTable = new javax.swing.JTable();
        empNameJLabel = new javax.swing.JLabel();
        empNameTxtField = new javax.swing.JTextField();
        createEmployeeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setText("Enterprise <Grey Sloan Medical Centre>");

        departmentJLabel.setText("Department :");

        departmentjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Engineering", "Accounts", "Equipment Maintenance", "Doctor", "Nurse", "Lab Technician" }));

        newEmployeeJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(newEmployeeJTable);
        if (newEmployeeJTable.getColumnModel().getColumnCount() > 0) {
            newEmployeeJTable.getColumnModel().getColumn(0).setResizable(false);
            newEmployeeJTable.getColumnModel().getColumn(1).setResizable(false);
            newEmployeeJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        empNameJLabel.setText("Employee Name :");

        createEmployeeBtn.setText("Create Employee");
        createEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createEmployeeBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(253, 253, 253)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(departmentJLabel)
                                    .addGap(37, 37, 37)
                                    .addComponent(departmentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(empNameJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(backBtn)
                                        .addComponent(empNameTxtField)))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentJLabel)
                    .addComponent(departmentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameJLabel)
                    .addComponent(empNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployeeBtn)
                    .addComponent(backBtn))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateDepartmentComboBox(){
        departmentjComboBox.removeAllItems();
        departmentjComboBox.addItem(DepartmentClass.Type.Accounts);
        departmentjComboBox.addItem(DepartmentClass.Type.Doctor);
        departmentjComboBox.addItem(DepartmentClass.Type.Engineering);
        departmentjComboBox.addItem(DepartmentClass.Type.EquipmentMaintenance);
        departmentjComboBox.addItem(DepartmentClass.Type.Lab);
        departmentjComboBox.addItem(DepartmentClass.Type.Nurse);
    }
    
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) newEmployeeJTable.getModel();
        
        model.setRowCount(0);
        
        for (DepartmentClass dept : ecosystem.getNetworkList().get(0).getDepartmentDirectory().getDepartmentList()){
            for(Employee emp: dept.getEmpDir().getEmployeeList())
            {
                Object[] row = new Object[3];
                row[0] = emp.getEmployeeId();
                row[1] = emp.getFirstName();
                row[2] = dept.getFullname();
                model.addRow(row);
            }
        }
    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        displayJPanel.remove(this);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeBtnActionPerformed
        DepartmentClass.Type departmentType = (DepartmentClass.Type) departmentjComboBox.getSelectedItem();
        String name = empNameTxtField.getText();
        for(DepartmentClass departmentClass: ecosystem.getNetworkList().get(0).getDepartmentDirectory().getDepartmentList())
        {
            if(departmentClass.getFullname().equalsIgnoreCase(departmentType.getValue()))
            {
               departmentClass.getEmpDir().createEmployee(name);
            }
        }
        populateTable();
    }//GEN-LAST:event_createEmployeeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createEmployeeBtn;
    private javax.swing.JLabel departmentJLabel;
    private javax.swing.JComboBox departmentjComboBox;
    private javax.swing.JLabel empNameJLabel;
    private javax.swing.JTextField empNameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable newEmployeeJTable;
    // End of variables declaration//GEN-END:variables
}
