/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysadminRole;

import Business.Department.DepartmentClass;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lsrajput
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private JPanel displayJPanel;
    Ecosystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel displayJPanel, UserAccount account, DepartmentClass department, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.displayJPanel = displayJPanel;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SysAdminWBJLabel = new javax.swing.JLabel();
        managePatientBtn = new javax.swing.JButton();
        manageEmpBtn = new javax.swing.JButton();
        manageUserBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        SysAdminWBJLabel.setText("System Admin Work Board");

        managePatientBtn.setText("Manage Patients");
        managePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePatientBtnActionPerformed(evt);
            }
        });

        manageEmpBtn.setText("Manage Employees");
        manageEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmpBtnActionPerformed(evt);
            }
        });

        manageUserBtn.setText("Manage User");
        manageUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Enterprise <Grey Sloan Medical Centre>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(managePatientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SysAdminWBJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addGap(361, 361, 361))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(SysAdminWBJLabel)
                .addGap(49, 49, 49)
                .addComponent(managePatientBtn)
                .addGap(33, 33, 33)
                .addComponent(manageEmpBtn)
                .addGap(29, 29, 29)
                .addComponent(manageUserBtn)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserBtnActionPerformed
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout)this.displayJPanel.getLayout();
        this.displayJPanel.add(new ManageUserAccounts(displayJPanel, ecosystem));
        layout.next(displayJPanel);
        
    }//GEN-LAST:event_manageUserBtnActionPerformed

    private void manageEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmpBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)this.displayJPanel.getLayout();
        this.displayJPanel.add(new ManageEmployeesJPanel(displayJPanel, ecosystem));
        layout.next(displayJPanel);
    }//GEN-LAST:event_manageEmpBtnActionPerformed

    private void managePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientBtnActionPerformed
        CardLayout layout = (CardLayout)this.displayJPanel.getLayout();
        this.displayJPanel.add(new ManagePatientsJPanel(displayJPanel, ecosystem));
        layout.next(displayJPanel);
    }//GEN-LAST:event_managePatientBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SysAdminWBJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmpBtn;
    private javax.swing.JButton managePatientBtn;
    private javax.swing.JButton manageUserBtn;
    // End of variables declaration//GEN-END:variables
}
