/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lsrajput
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    JPanel displayJPanel;
    Enterprise enterprise;
    Ecosystem ecosystem;
    public AdminWorkAreaJPanel(JPanel displayPanel, Ecosystem ecosystem) {
        initComponents();
        this.displayJPanel = displayPanel;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminWorkAreaDashJLabel = new javax.swing.JLabel();
        ManageEnterpriseBtn = new javax.swing.JButton();
        manageSysAdminBtn = new javax.swing.JButton();

        adminWorkAreaDashJLabel.setText("Admin Work Area Dashboard");

        ManageEnterpriseBtn.setText("Manage Enterprise");
        ManageEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterpriseBtnActionPerformed(evt);
            }
        });

        manageSysAdminBtn.setText("Manage Enterprise Admin/System Admin");
        manageSysAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSysAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminWorkAreaDashJLabel)
                    .addComponent(ManageEnterpriseBtn)
                    .addComponent(manageSysAdminBtn))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminWorkAreaDashJLabel)
                .addGap(18, 18, 18)
                .addComponent(ManageEnterpriseBtn)
                .addGap(18, 18, 18)
                .addComponent(manageSysAdminBtn)
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)this.displayJPanel.getLayout();
        displayJPanel.add(new ManageEnterpriseJPanel(displayJPanel,ecosystem));
        layout.next(displayJPanel);
    }//GEN-LAST:event_ManageEnterpriseBtnActionPerformed

    private void manageSysAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSysAdminBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)this.displayJPanel.getLayout();
        displayJPanel.add(new ManageEnterpriseAdminJPanel(displayJPanel,ecosystem));
        layout.next(displayJPanel);
    }//GEN-LAST:event_manageSysAdminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEnterpriseBtn;
    private javax.swing.JLabel adminWorkAreaDashJLabel;
    private javax.swing.JButton manageSysAdminBtn;
    // End of variables declaration//GEN-END:variables
}
